config/routes.rb
Rails.application.routes.draw do

  root 'sessions#landing'
  get '/landingcreator' => 'sessions#landingcreator'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/login-creator' => 'sessions#newcreator'
  post '/login-creator' => 'sessions#createcreator'
  delete '/logout' => 'sessions#destroy'
  delete '/logout-creator' => 'sessions#destroycreator'
  get '/home' => 'users#home'
  get '/signup' => 'users#new' 
  get '/home-creator' => 'creators#home' 
  get '/signup-creator' => 'creators#new' 
  get '/auth/:provider/callback' => 'sessions#googlecreate'

  resources :users
  resources :creators
  resources :albums
  resources :podcasts
  resources :singles
  
  resources :songs, only: [:index, :show]

  resources :albums do
    resources :songs, only: [:new, :create, :index, :show, :edit, :destroy]
  end
end

app/views/layouts/content/_albums.html.erb
<h2>Albums</h2>
<div id="albums-container" class="content-container">
    <% if object.length > 0 %>
    <% object.each do |album| %>
        <%= link_to album_path(album) do %>
        <div class="content-container-item">
            <h3><%= album.name %></h3>
            <p><%= album.category %></p>
            <p><%= album.release_date %></p>
        </div>
        <% end %>
    <% end %>
    <% else %>
        <% if logged_in_creator? %>
            <p>Create or add your first album!</p>
        <% elsif logged_in_user? %>
            <p>No released albums</p>
        <% end %>
    <% end %>
</div>

app/views/layouts/content/_singles.html.erb
<h2>Singles</h2>
<div id="singles-container" class="content-container">
    <% if object.length > 0 %>
    <% object.each do |single| %>
        <%= link_to single_path(single) do %>
        <div class="content-container-item">
            <h3><%= single.name %></h3>
            <p><%= single.category %></p>
            <p><%= single.release_date %></p>
        </div>
        <% end %>
    <% end %>
    <% else %>
        <% if logged_in_creator? %>
            <p>Create or add your first single!</p>
        <% elsif logged_in_user? %>
            <p>No released singles</p>
        <% end %>
    <% end %>
</div>