config/routes.rb
Rails.application.routes.draw do

  root 'sessions#landing'
  get '/landingcreator' => 'sessions#landingcreator'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/login-creator' => 'sessions#newcreator'
  post '/login-creator' => 'sessions#createcreator'
  delete '/logout' => 'sessions#destroy'
  delete '/logout-creator' => 'sessions#destroycreator'
  get '/home' => 'users#home'
  get '/signup' => 'users#new' 
  get '/home-creator' => 'creators#home' 
  get '/signup-creator' => 'creators#new' 
  get '/auth/:provider/callback' => 'sessions#googlecreate'

  resources :users
  resources :creators
  resources :albums
  resources :podcasts
  resources :singles
  
  resources :songs, only: [:index, :show]

  resources :albums do
    resources :songs, only: [:new, :create, :index, :show, :edit, :destroy]
  end
end

app/models/album.rb
class Album < ApplicationRecord

    belongs_to :creator
    has_many :users
    has_many :songs

    validates :name, :category, presence: true
    validates :name, length: { maximum: 50 }
    validates :category, length: { maximum: 50 }

    scope :released_albums, -> {where(released: true )}
    scope :edm_music, -> {where(category: "EDM")}

    def self.released_album_songs
        @songs = []
        self.where(released: true).each do |album|
            album.songs.each do |song|
                @songs << song
            end
        end
        @songs
    end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :check_unauthenticated_redirect_needed, only: [:index, :show]
    before_action :check_if_logged_in_creator, only: [:edit, :destroy]
    before_action :check_album_exists, only: [:edit, :destroy]
    before_action :check_if_creator_owns_album, only: [:edit, :destroy]

    def index
        if params[:category].present?
            @selected_category = params[:category].downcase!
            if @selected_category == "edm"
                @albums = Album.edm_music   
            end
        else
            @albums = Album.released_albums
        end
    end

    def new
        if logged_in_creator?
            @album = Album.new
        else
            redirect_to home_path
        end
    end

    def create
        if logged_in_creator?
            @album = current_creator.albums.build(album_params)
            if @album.save
                redirect_to album_path(@album)
            else
                render :new
            end
        else
            redirect_to '/'
        end
    end

    def show
        check_album_exists
    end

    def edit
    end

    def destroy
        @album.destroy
        redirect_to albums_path
    end
    
    private

    def check_if_logged_in_creator
        if !logged_in_creator?
            redirect_to home_path
        end
    end

    def check_album_exists
        @album = Album.find_by_id(params[:id])
        if !@album
            redirect_to home_path
        end
    end

    def check_if_creator_owns_album
        @album = Album.find_by_id(params[:id])
        if @album
            if @album.creator_id != session[:creator_id]
                redirect_to home_path
            end
        else    
            redirect_to home_path
        end
    end
    
    def album_params
        params.require(:album).permit(:name, :category, :release_date, :released)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/edit.html.erb
<h1>album edit page</h1>

<%= link_to "Delete Album", album_path(@album), :method => 'delete'%>

app/views/albums/index.html.erb
<div id="albums-container">
    <%= render partial: 'layouts/home/recents', locals: {object: @albums} %>
</div>

app/views/albums/new.html.erb
<h1>Create New Album</h1>
<%= form_for(@album) do |f| %>
    <%= render partial: 'layouts/errors', locals: {object: @album} %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :category %>
    <%= f.text_field :category %>
    <%= f.label :release_date %>
    <%= f.text_field :release_date %>
    <%= f.label :relased %>
    <%= f.check_box :released %>
    <%= f.submit "Create Album" %>
<% end %>

app/views/albums/show.html.erb
<div id="album-show-container">
    <div id="album-show-container-header">
        <h3>Album Name: <%= @album.name %></h3>
        <% if logged_in_creator? %>
            <%= link_to 'Edit Album', "/albums/#{@album.id}/edit" %>
        <% end %>
    </div>
    <div id="album-show-container-songs">
        <h4>All Songs</h4>
        <% @album.songs.each do |song|%>
        
        <div class="album-show-container-song-item">
            <p><%= song.name %></p>
            <% if logged_in_creator? %>
                <%= link_to 'Edit Song', "/albums/#{@album.id}/songs/#{song.id}/edit" %>
            <% end %>
        </div>
        <% end %>
        <% if logged_in_creator? %>
            <%= link_to 'Add Song to Album', new_album_song_path(@album) %>
        <% end %>
    </div>
</div>