config/routes.rb
Rails.application.routes.draw do

  root 'sessions#landing'
  get '/landingcreator' => 'sessions#landingcreator'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/login-creator' => 'sessions#newcreator'
  post '/login-creator' => 'sessions#createcreator'
  delete '/logout' => 'sessions#destroy'
  delete '/logout-creator' => 'sessions#destroycreator'
  get '/home' => 'users#home'
  get '/signup' => 'users#new' 
  get '/home-creator' => 'creators#home' 
  get '/signup-creator' => 'creators#new' 
  get '/auth/:provider/callback' => 'sessions#googlecreate'

  resources :users
  resources :creators
  resources :albums
  resources :podcasts
  resources :singles
  
  resources :songs, only: [:index, :show]

  resources :albums do
    resources :songs, only: [:new, :create, :index, :show, :edit, :destroy]
  end
end

app/views/layouts/_albums.html.erb
<h2>Albums</h2>
<div id="albums-container">
    <% if object.length > 0 %>
    <% object.each do |album| %>
        <div class="albums-container-item">
                <h3><%= album.name %></h3>
                <p><%= album.category %></p>
                <p>Released: <%= album.release_date %></p>
        </div>
    <% end %>
    <% else %>
        <% if logged_in_creator? %>
            <p>Create or add your first album!</p>
        <% elsif logged_in_user? %>
            <p>No released albums</p>
        <% end %>
    <% end %>
</div>

app/views/layouts/_errors.html.erb
<ul>
    <% object.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
    <% end%>
</ul>

app/views/layouts/_footer.html.erb
<div id="footer-container">

    <div class="footer-container-item">
        <h3 class="footer-container-header">Our Company</h3>
        <p>Our Blog</p>
        <p>Search Page</p>
    </div>
    <div class="footer-container-item">
        <h3 class="footer-container-header">Information</h3>
        <p>Privacy</p>
        <p>FAQs</p>
    </div>
    <div class="footer-container-item">
        <h3 class="footer-container-header">Categories</h3>
        <%= link_to 'Creators', login_creator_path %>
        <p>Albums</p>
        <p>New Releases</p>
    </div>
        <div class="footer-container-item">
        <h3 class="footer-container-header">Contact Us</h3>
        <p>Loudr</p>
        <p>123 Anywhere Street</p>
        <p>Lehi UT, 84043</p>
        <p>1-800-555-5555</p>
    </div>
</div>

app/views/layouts/_header.html.erb
<div id="header-container">
    <%= link_to home_path do %>
        <div id="header-container-logo"></div>
    <% end %>
    <div id="header-container-buttons">
        <% if logged_in_creator? || logged_in_user? %>
            <% if logged_in_creator? %>
                <%= link_to "New Album", new_album_path %>       
                <%= link_to 'Log Out', logout_creator_path, method: :delete, class: 'header-container-button'%>
            <% elsif logged_in_user? %>
                <%= link_to 'Log Out', logout_path, method: :delete, class: 'header-container-button' %>
            <% end%>
        <% else %>
            <% if for_creator_url? %>
                <%= link_to "Get Access", signup_creator_path %>
                <%= link_to "Log In", login_creator_path %>
            <% else %>
                <%= link_to "Sign Up", signup_path, class: 'header-container-button' %>
                <%= link_to "Log In", login_path, class: 'header-container-button' %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<div id="navbar-container">
    <div id="navbar-container-main-menu" class="navbar-container-section">
        <h4>Main Menu</h4>
        <%= link_to home_path do %>
            <div id="navbar-cotainer-selection-home" class="navbar-container-selection-item">
                <p>Home</p>
            </div>
        <% end %>
        <%= link_to songs_path do %>
            <div class="navbar-container-selection-item">
                <p>Songs</p>
            </div>
        <% end %>
        <%= link_to albums_path do %>
            <div class="navbar-container-selection-item">
                <p>Albums</p>
            </div>
        <% end %>
        <%= link_to creators_path do %>
            <div class="navbar-container-selection-item">
                <p>Creators</p>
            </div>
        <% end %>
        <%= link_to singles_path do %>
            <div class="navbar-container-selection-item">
                <p>Singles</p>
            </div>
        <% end %>
        <%= link_to podcasts_path do %>
            <div class="navbar-container-selection-item">
                <p>Podcasts</p>
            </div>
        <% end %>
    </div>
    <div id="navbar-container-yours" class="navbar-container-section">
        <h4>Yours</h4>
        <%= link_to podcasts_path do %>
            <div class="navbar-container-selection-item">
                <p>Favorites</p>
            </div>
        <% end %>
        <%= link_to podcasts_path do %>
            <div class="navbar-container-selection-item">
                <p>Play History</p>
            </div>
        <% end %>
        <%= link_to podcasts_path do %>
            <div class="navbar-container-selection-item">
                <p>Download Items</p>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_player.html.erb
<div id="player-container">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loudr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  </head>
  <body>
    <%= render "layouts/header" %>
    <div id="application-container">
      <% if authenticated_user_or_creator? %>
        <%= render "layouts/navbar" %>
      <% end %>
      <div id="content-container">
        <%= yield %>
      </div>
    </div>
    <% if authenticated_user_or_creator? %>
      <%= render "layouts/player" %>
    <% end %>
    <% if !authenticated_user_or_creator? %>
        <%= render "layouts/footer" %>
    <% end %>  
  </body>
</html>